### Install chardet library to detect the encoding of the dataset.

### This helps us automatically identify the correct encoding form

### Using the correct encoding ensures that the data is read properly (avoid Unicode errors or corrupted text)

### This step improves data quality and helps achieve better model performance.

In [1]:
! pip install chardet

Defaulting to user installation because normal site-packages is not writeable
Collecting chardet
  Downloading chardet-7.4.3-cp313-cp313-win_amd64.whl.metadata (9.4 kB)
Downloading chardet-7.4.3-cp313-cp313-win_amd64.whl (944 kB)
   ---------------------------------------- 0.0/944.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/944.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/944.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/944.2 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/944.2 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/944.2 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/944.2 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/944.2 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/944.2 kB ? eta -:--:--
   --------------------- ---------------- 524.3/944.2 kB 267.9 kB/s eta 0:00:02
   --------------------- ---------------- 524.3/944.2 kB 267.9 kB/s eta 0:00:02
   --------------------- ---------------- 524.3/944.2 kB 267.9 kB/s eta 0:00:02
   --------------------- ---------------- 524.3/944.2 kB 267.9 kB/s eta 0:00:02
   --------------------- ---------------- 524.3/944.2 kB 267.9 kB/s eta 0:00:02
   --------------------- ---------------- 524.3/944.2 kB 267.9 kB/s eta 0:00:02
   ------------------------------- ------ 786.4/944.2 kB 223.8 kB/s eta 0:00:01
   ------------------------------- ------ 786.4/944.2 kB 223.8 kB/s eta 0:00:01
   ------------------------------- ------ 786.4/944.2 kB 223.8 kB/s eta 0:00:01
   ---------------------------------------- 944.2/944.2 kB 230.7 kB/s  0:00:03
Installing collected packages: chardet
Successfully installed chardet-7.4.3

In [11]:
from webencodings import Encoding

import chardet
import pandas as pd

with open("spam.csv","rb") as data:
    kind_of_encoding = chardet.detect(data.read())['encoding']



df = pd.read_csv("spam.csv", encoding= kind_of_encoding)
print(kind_of_encoding)

iso8859-15

In [12]:
df.head(15)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
6,ham,Even my brother is not like to speak with me. ...,NaN,NaN,NaN
7,ham,As per your request 'Melle Melle (Oru Minnamin...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN
10,ham,I'm gonna be home soon and i don't want to tal...,NaN,NaN,NaN
11,spam,"SIX chances to win CASH! From 100 to 20,000 po...",NaN,NaN,NaN
12,spam,URGENT! You have won a 1 week FREE membership ...,NaN,NaN,NaN
13,ham,I've been searching for the right words to tha...,NaN,NaN,NaN
14,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,NaN,NaN,NaN

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   label          5572 non-null   str
 1   message        5572 non-null   str
 2   clean_message  5572 non-null   str
dtypes: str(3)
memory usage: 130.7 KB

In [28]:
df.isnull().count()

label            5572
message          5572
clean_message    5572
dtype: int64

### Remove unnecessary "Unnamed" columns created due to empty columns in CSV.
### These columns contain no useful information for the model.

## to drop all columns prefix "Unnamed"         -->  df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [13]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [14]:
df.head(15)

      v1                                                 v2
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...
5   spam  FreeMsg Hey there darling it's been 3 week's n...
6    ham  Even my brother is not like to speak with me. ...
7    ham  As per your request 'Melle Melle (Oru Minnamin...
8   spam  WINNER!! As a valued network customer you have...
9   spam  Had your mobile 11 months or more? U R entitle...
10   ham  I'm gonna be home soon and i don't want to tal...
11  spam  SIX chances to win CASH! From 100 to 20,000 po...
12  spam  URGENT! You have won a 1 week FREE membership ...
13   ham  I've been searching for the right words to tha...
14   ham                I HAVE A DATE ON SUNDAY WITH WILL!!

In [16]:
df.columns = ['label', 'message']
df.head(15)

   label                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...
5   spam  FreeMsg Hey there darling it's been 3 week's n...
6    ham  Even my brother is not like to speak with me. ...
7    ham  As per your request 'Melle Melle (Oru Minnamin...
8   spam  WINNER!! As a valued network customer you have...
9   spam  Had your mobile 11 months or more? U R entitle...
10   ham  I'm gonna be home soon and i don't want to tal...
11  spam  SIX chances to win CASH! From 100 to 20,000 po...
12  spam  URGENT! You have won a 1 week FREE membership ...
13   ham  I've been searching for the right words to tha...
14   ham                I HAVE A DATE ON SUNDAY WITH WILL!!

In [ ]:
import re

def clean_text(text):

    text = text.lower()                             # all letter small

    text = re.sub(r'http\S+', '', text)             #remove links 

    text = re.sub(r'\d+', '', text)                 #remove numbers 

    text = re.sub(r"[^\w\s']", '', text)             #remove not letter, numbers and spase and '  (\w\s = \W)

    text = re.sub(r'\s+', ' ', text).strip()        #remove Extra Space 

    return text

In [23]:
df["clean_message"] = df["message"].apply(clean_text)
df.head(15)

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...
10,ham,I'm gonna be home soon and i don't want to tal...,i'm gonna be home soon and i don't want to tal...
11,spam,"SIX chances to win CASH! From 100 to 20,000 po...",six chances to win cash from to pounds txt csh...
12,spam,URGENT! You have won a 1 week FREE membership ...,urgent you have won a week free membership in ...
13,ham,I've been searching for the right words to tha...,i've been searching for the right words to tha...
14,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,i have a date on sunday with will

### Now we do Tokenization

In [29]:
! pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\dell\AppData\Roaming\Python\Python313\site-packages (3.9.1)
Requirement already satisfied: click in C:\Users\dell\AppData\Roaming\Python\Python313\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in C:\Users\dell\AppData\Roaming\Python\Python313\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\dell\AppData\Roaming\Python\Python313\site-packages (from nltk) (2025.8.29)
Requirement already satisfied: tqdm in C:\Users\dell\AppData\Roaming\Python\Python313\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in C:\Users\dell\AppData\Roaming\Python\Python313\site-packages (from click->nltk) (0.4.6)

In [33]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
df["word_token"] = df["clean_message"].apply(word_tokenize)
df.head(15)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,label,message,clean_message,token,word_token
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o...","[go, until, jurong, point, crazy, available, o..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[ok, lar, joking, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, in, a, wkly, comp, to, win, fa, ...","[free, entry, in, a, wkly, comp, to, win, fa, ..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t...","[u, dun, say, so, early, hor, u, c, already, t..."
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, i, do, n't, think, he, goes, to, usf, he...","[nah, i, do, n't, think, he, goes, to, usf, he..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, there, darling, it, 's, been, w...","[freemsg, hey, there, darling, it, 's, been, w..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, my, brother, is, not, like, to, speak, ...","[even, my, brother, is, not, like, to, speak, ..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[as, per, your, request, 'melle, melle, oru, m...","[as, per, your, request, 'melle, melle, oru, m..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, as, a, valued, network, customer, you...","[winner, as, a, valued, network, customer, you..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[had, your, mobile, months, or, more, u, r, en...","[had, your, mobile, months, or, more, u, r, en..."
10,ham,I'm gonna be home soon and i don't want to tal...,i'm gonna be home soon and i don't want to tal...,"[i, 'm, gon, na, be, home, soon, and, i, do, n...","[i, 'm, gon, na, be, home, soon, and, i, do, n..."
11,spam,"SIX chances to win CASH! From 100 to 20,000 po...",six chances to win cash from to pounds txt csh...,"[six, chances, to, win, cash, from, to, pounds...","[six, chances, to, win, cash, from, to, pounds..."
12,spam,URGENT! You have won a 1 week FREE membership ...,urgent you have won a week free membership in ...,"[urgent, you, have, won, a, week, free, member...","[urgent, you, have, won, a, week, free, member..."
13,ham,I've been searching for the right words to tha...,i've been searching for the right words to tha...,"[i, 've, been, searching, for, the, right, wor...","[i, 've, been, searching, for, the, right, wor..."
14,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,i have a date on sunday with will,"[i, have, a, date, on, sunday, with, will]","[i, have, a, date, on, sunday, with, will]"

### part of stop word removal

In [ ]:
from nltk.corpus import stopwords
nltk.download("stopwords")
stop_words = set(stopwords.words("english"))
print(stop_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...

{'too', "mustn't", 'have', 'his', "it's", 'd', 'myself', 'through', 'what', "you'd", 'until', 'ourselves', 'yours', "you've", "you're", 'y', "didn't", 'do', 'a', 'mustn', 'are', 'before', 'him', 'it', 'wouldn', 'hasn', 'further', 'mightn', "we'd", 'ours', 'once', 'weren', 'theirs', 'with', 'my', 'after', 'over', "doesn't", 'did', 'we', 'under', 'while', 'any', 'same', 'that', 'who', "i'd", 'o', 'an', 'from', 'in', 'when', 'll', 's', 'haven', 'they', 'all', 'he', 'more', 't', "it'd", "she'd", "hasn't", 'the', 'their', 'there', 'were', 'ain', 'didn', 'few', 'up', "he'd", 'ma', 'whom', "mightn't", 'be', 'only', 'doesn', 'been', 'this', "wouldn't", "we've", 'shouldn', 'into', 'aren', 'needn', 'against', "i'm", 'yourselves', "should've", "weren't", 'where', 'here', "needn't", "you'll", 'again', 'is', 'don', 'himself', 'our', 'its', 'wasn', 'had', "they'd", 'them', 'you', 'at', 'below', "shouldn't", "haven't", 'each', 'hadn', "hadn't", "he'll", 'your', 'themselves', 'if', 'and', 'those', 'to', "couldn't", 'has', 'shan', "won't", 'as', 'i', "i've", 'why', "she's", "that'll", 'having', 'than', 've', 'does', 'by', 'just', 'about', 'because', 'isn', 'very', 'was', 'yourself', 're', 'itself', 'which', 'both', 'will', "they've", 'during', 'me', 'won', 'she', "we're", 'nor', 'down', "he's", "don't", 'hers', 'but', 'couldn', 'so', 'not', 'other', 'for', 'some', 'being', 'herself', 'out', "we'll", 'no', "i'll", 'her', 'can', 'am', "isn't", 'or', 'own', 'then', 'such', "she'll", "wasn't", "aren't", 'of', 'now', "they're", 'these', 'on', 'above', 'most', "shan't", 'doing', "they'll", 'how', 'should', 'off', 'between', 'm', "it'll"}

[nltk_data]   Unzipping corpora\stopwords.zip.

In [40]:
df["word_token"] = df["word_token"].apply(
    lambda words: [word for word in words if word not in stop_words])
df.head(15)

,label,message,clean_message,token,word_token
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o...","[go, jurong, point, crazy, available, bugis, n..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[ok, lar, joking, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, in, a, wkly, comp, to, win, fa, ...","[free, entry, wkly, comp, win, fa, cup, final,..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t...","[u, dun, say, early, hor, u, c, already, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, i, do, n't, think, he, goes, to, usf, he...","[nah, n't, think, goes, usf, lives, around, th..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, there, darling, it, 's, been, w...","[freemsg, hey, darling, 's, week, 's, word, ba..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, my, brother, is, not, like, to, speak, ...","[even, brother, like, speak, treat, like, aids..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[as, per, your, request, 'melle, melle, oru, m...","[per, request, 'melle, melle, oru, minnaminung..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, as, a, valued, network, customer, you...","[winner, valued, network, customer, selected, ..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[had, your, mobile, months, or, more, u, r, en...","[mobile, months, u, r, entitled, update, lates..."
10,ham,I'm gonna be home soon and i don't want to tal...,i'm gonna be home soon and i don't want to tal...,"[i, 'm, gon, na, be, home, soon, and, i, do, n...","['m, gon, na, home, soon, n't, want, talk, stu..."
11,spam,"SIX chances to win CASH! From 100 to 20,000 po...",six chances to win cash from to pounds txt csh...,"[six, chances, to, win, cash, from, to, pounds...","[six, chances, win, cash, pounds, txt, csh, se..."
12,spam,URGENT! You have won a 1 week FREE membership ...,urgent you have won a week free membership in ...,"[urgent, you, have, won, a, week, free, member...","[urgent, week, free, membership, å, prize, jac..."
13,ham,I've been searching for the right words to tha...,i've been searching for the right words to tha...,"[i, 've, been, searching, for, the, right, wor...","['ve, searching, right, words, thank, breather..."
14,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,i have a date on sunday with will,"[i, have, a, date, on, sunday, with, will]","[date, sunday]"